### ISSUE TITLE
Could not execute entrypoint stage 'main' due to errors

### ISSUE THREAD

**Issue by jimpnotsimp** [MehVahdJukaar/supp_squared#18]
Supplementaries Squared crashes upon launching the game: 

```
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'suppsquared'! 
```
Crash Report:

[crash-2023-06-24_22.20.05-client.txt](https://github.com/MehVahdJukaar/supp_squared/files/11857213/crash-2023-06-24_22.20.05-client.txt)

**Comment by MehVahdJukaar** [comment]
Use latest version of all my mods also use 1.20.1
