### ISSUE TITLE
Installing supplementaries squared removes item shelves from JEI

### ISSUE THREAD

**Issue by SilentSimulacrum** [MehVahdJukaar/supp_squared#19]
Shelves do not appear in JEI but are still craftable.

Steps to reproduce:
1. Launch game with JEI and Supplementaries
2. Look in JEI and observe the default item shelf
3. Close game, add Supplementaries Squared and re-launch
4. Look in JEI and observe none of the shelves showing up

Mod Versions:
JEI: 15.2.0.23
Supplementaries: 2.5.18
Supplementaries Squared: 1.1.5
Forge: 47.10

**Comment by MehVahdJukaar** [comment]
fixed on latest 1.20.1 version
