### ISSUE TITLE
Plaque text placed in the wrong spot

### ISSUE THREAD

**Issue by PaleAsphodel** [MehVahdJukaar/supp_squared#20]
Hello,
I'm using the latest version (1.20 1.1.6). It appears the plaque text is not placed on the plaque itself, but on the bottom face of the block.

![2023-08-06_11 22 54](https://github.com/MehVahdJukaar/supp_squared/assets/141549458/eb96f1cb-be33-4379-b3cb-0db029660ea9)

Thanks!

**Comment by MehVahdJukaar** [comment]
fixed
