### ISSUE TITLE
Sconce colour not matching (might be intended)

### ISSUE THREAD

**Issue by PaleAsphodel** [MehVahdJukaar/supp_squared#21]
Hello,
I'm using the latest version (1.20 1.1.6).

It appears that for some sconces, the fire particles match the torch colour (blue for soul sconce and green for green sconce). However, for the ender sconce, glowstone sconce and brass sconce, the fire particles are just their default colour and don't match the purple/yellow/greenish tint of the sconce texture itself, giving it a slightly mismatched look.
This might be intended, but I'm reporting it anyway just in case. Those sconce variants seem only obtainable through commands, but I find them rather useful for ambiance and decoration.

![2023-08-06_11 23 24](https://github.com/MehVahdJukaar/supp_squared/assets/141549458/f52256e2-07df-4c7c-931e-c4c900c5391f)

Thanks!

**Comment by MehVahdJukaar** [comment]
those are compat blocks. they arent available if you dont have the correct mods on

**Comment by MehVahdJukaar** [comment]
in latest updae all sconces wont even be registered when the right mods are not on now
