### ISSUE TITLE
[Quilt] Crash on startup

### ISSUE THREAD

**Issue by SplendidAlakey** [MehVahdJukaar/supp_squared#7]
**MC** 1.19.2
**QFAPI** 4.0.0-beta.29
**Supplementaries Squared** 1.0.7

To reproduce simply install the mod and its dependencies, then run the game.

This doesn't seem to be the same crash as the other 2, as this one only happens with QFAPI.

The issue doesn't happen if you replace QFAPI with FAPI. It doesn't seem to be caused by QFAPI being 1 version behind, because the same version of FAPI itself doesn't crash.

Let me know, if this needs to be reported to Quilt, instead.

Logs: https://gist.github.com/SplendidAlakey/eb38d7dd4b0185cf1148c9b80873b5a2

**Comment by MehVahdJukaar** [comment]
try with new supplementaries version

**Comment by SplendidAlakey** [comment]
Updated both Moonlight and Supplementaries, still crashing, but I noticed that Supplementaries update has the same version number and changelog. Perhaps a wrong file got uploaded?

![image](https://user-images.githubusercontent.com/86702831/227716298-e79cf2aa-9d19-4bab-b44e-f3873dd52d86.png)

**Comment by MehVahdJukaar** [comment]
CF was slow and it uploaded the same file twice. Can you send the new log?

**Comment by SplendidAlakey** [comment]
Oddly enough, I'm not crashing in a large modpack, but I do, when running only Moonlight + Supplementaries + Supplementaries Squared. It's like I'm missing a dependency? Not sure at this point. Updated the above link with the new logs, using newest versions of everything.

**Comment by MehVahdJukaar** [comment]
Does this happen on fabric?

**Comment by SplendidAlakey** [comment]
No, happens only on Quilt and specifically with QFAPI. If I replace QFAPI with regular FAPI it works fine. And like mentioned above, for some reason in a modpack it also works fine.

**Comment by MehVahdJukaar** [comment]
i need latest.log

**Comment by SplendidAlakey** [comment]
https://gist.github.com/SplendidAlakey/eb38d7dd4b0185cf1148c9b80873b5a2#file-latest-log

**Comment by Sunconure11** [comment]
I'm still getting this as well.

**Comment by Fortun4tus** [comment]
https://github.com/MehVahdJukaar/supp_squared/issues/11 (my issue) is probably the same.

**Comment by SplendidAlakey** [comment]
Fixed in 1.0.14.
