### ISSUE TITLE
Item Shelves Recipes

### ISSUE THREAD

**Issue by ereese99** [MehVahdJukaar/supp_squared#9]
None of the item shelf recipes are available, the only one that exists is the normal one, and the recipe is a blank crafting table for 2 item shelves (unlimited shelves!). This is with the newest version of this mod, Supplementaries, and Moonlight Lib.

**Comment by MehVahdJukaar** [comment]
This with latest version?

**Comment by ereese99** [comment]
Supplementaries 2.2.64
Supplementaries Squared 1.0.10
Moonlight Lib 2.2.27

Fabric 0.14.18
Minecraft 1.19.2

**Comment by MehVahdJukaar** [comment]
Try latest

**Comment by ianm1647** [comment]
also experiencing this on forge

Supplementaries 2.3.1
Supp Squared 1.0.10
Moonlight Lib 2.2.28
Forge 43.2.8
Minecraft 1.19.2

except its different, its saying these are blank tags

![image](https://user-images.githubusercontent.com/15511983/230182055-a9369560-5fbf-4859-9b44-e389132591b7.png)

**Comment by antauriprime** [comment]
Same here. The funniest thing is that the base shelves can actually be crafted with 3 barrier blocks as it is shown in the REI/JEI recipe. Feels rather absurd 😄
Hope it's not too hard of a bug to fix. In the meantime, guess I'll have to resort to "smuggling" the shelves in via the "Open To LAN" feature. Oh well.

Supplementaries 2.2.64
Suppsquared 1.0.10
Moonlight 2.2.27
Forge 43.2.8
Minecraft 1.19.2

**Comment by MehVahdJukaar** [comment]
use latest version of supplementaries

**Comment by antauriprime** [comment]
> use latest version of supplementaries

The issue persists with the latest versions of of both Supplementaries and Supplementaries Squared.

![Screenshot_6](https://user-images.githubusercontent.com/30935221/230901148-e05b65d1-0b89-4274-a61c-a9443fb4a667.png)
![Screenshot_5](https://user-images.githubusercontent.com/30935221/230901152-7fdbf7b8-a727-4c19-97ec-91a5c8e17f41.png)

**Comment by MehVahdJukaar** [comment]
Idk why I can't replicate this. So just is the recipe not working of just it's Jei view?

**Comment by antauriprime** [comment]
### Recipes don't work correctly, it is not a visual only bug.

![Screenshot_8](https://user-images.githubusercontent.com/30935221/230909331-0e0d402c-0f44-428e-aed5-bbd4a9942e6b.png)
![Screenshot_7](https://user-images.githubusercontent.com/30935221/230909347-ec084324-45e6-444b-aea5-57f45bacfd66.png)

### Only the original oak shelf has a recipe, btw. All other selves only have 3 tags and no recipes.

![Screenshot_10](https://user-images.githubusercontent.com/30935221/230909691-0fa77d66-21cf-40b1-a112-32e6cef6b2fb.png)
![Screenshot_11](https://user-images.githubusercontent.com/30935221/230909707-b3834170-8d9e-4f2a-84be-f3281bd07d8e.png)
![Screenshot_12](https://user-images.githubusercontent.com/30935221/230909730-60b1eb16-55e1-4a67-9d4f-c0869aee8624.png)


> Also what does it say when you hover over those barriers

### There you go:

![Screenshot_9](https://user-images.githubusercontent.com/30935221/230909409-9ed3912d-10be-409a-b473-d39d2cdd97f3.png)

**Comment by antauriprime** [comment]
Not sure if that of any relevance, but it would seem that the shelves actually only have 2 tags. It's just that the supplementaries:item_shelves tag is duplicated in the REI GUI for some reason. Doubt it has anything to do with the issue though, because supplementaries:hanging_signs appears to be duplicated as well, yet the recipes work flawlessly.

**Comment by MehVahdJukaar** [comment]
I see what the problem is. My built script wasnt uploading stuff to CF... skpiied 4 updates because of that wtf

**Comment by antauriprime** [comment]
Well, glad that this got uncovered sooner rather than later.

**Comment by antauriprime** [comment]
Updating to Suppsquared-1.19.2-1.0.14 fixed the issue for me. Thanks for your work!

![image](https://user-images.githubusercontent.com/30935221/230928775-b180ba42-e64c-41e9-bfd1-77cd343b34be.png)
![image](https://user-images.githubusercontent.com/30935221/230931530-f73c4dcc-da13-4512-aa99-a7420cdd1081.png)

**Comment by MehVahdJukaar** [comment]
Awesome

**Comment by ereese99** [comment]
Works for me as well!
